{{- if and (.Values.slave.enabled) (.Values.slave.ingress.enabled) }}
# Defines the ingress for the Alfresco Search (Solr) App
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr-slave
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/rewrite-target: /solr
    nginx.ingress.kubernetes.io/auth-secret: {{ template "alfresco-search.fullName" . }}-solr-slave
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Alfresco Search Services"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.slave.ingress.whitelist_ips }}

spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.slave.ingress.path }}
        backend:
          serviceName: {{ template "alfresco-search.fullName" . }}-solr-slave
          servicePort: {{ .Values.slave.service.externalPort }}
{{- end }}